print("--"*50)
mn1=int(input("Give me the first number you want to multiply for:"))
mn2=int(input("Give me the second number you want to multiply for:"))
print("The answer to your query is:", mn1*mn2)
print("--"*50)
dn1=float(input("Give me the first number you want to divide for:"))
dn2=float(input("Give me the second number you want to divide for:"))
print("The answer to your query is:", dn1/dn2)
print("--"*50)
drn1=int(input("Give me the first number you want to divide for (without the remainder):"))
drn2=int(input("Give me the second n0.5umber you want to divide for (without the remainder):"))
print("The answer to your query is:", drn1//drn2)
print("--"*50)
dmn1=int(input("Give me the first number you want to divide and get the modulo for:"))
dmn2=int(input("Give me the second number you want to divide and get the modulo for:"))
print("The answer to your query is:", dmn1%dmn2)
print("--"*50)
an1=int(input("Give me the first number you want to add for:"))
an2=int(input("Give me the second number you want to add for:"))
print("The answer to your query is:", an1+an2)
print("--"*50)
sn1=int(input("Give me the first number you want to subtract for:"))
sn2=int(input("Give me the second number you want to subtract for:"))
print("The answer to your query is:", sn1-sn2)
print("--"*50)
print("Renan Faria Schmidt")